language: php
php:
  - 5.6
  - 7.0
  - 7.2

env:
  - PHP_UNIT_VERSION="5.7"
  - PHP_UNIT_VERSION="6.0"
  - PHP_UNIT_VERSION="7.0"

matrix:
  exclude:
  - env: PHP_UNIT_VERSION="6.0"
    php: 5.6
  - env: PHP_UNIT_VERSION="7.0"
    php: 5.6
  - env: PHP_UNIT_VERSION="7.0"
    php: 7.0

before_install:
   - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then pear config-set preferred_state snapshot && yes "" | pecl install mcrypt ; fi

before_script:
  - composer require phpunit/phpunit:${PHP_UNIT_VERSION}
  - composer install --dev
